# Generated by Django 5.0.7 on 2024-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('competency', models.CharField(max_length=255)),
            ],
        ),
    ]
