# Generated by Django 5.1 on 2024-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('question_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('question_3', models.CharField(max_length=255)),
                ('question_4', models.CharField(max_length=255)),
                ('question_5', models.CharField(max_length=255)),
                ('question_6', models.CharField(max_length=255)),
                ('question_7', models.CharField(max_length=255)),
                ('question_8', models.CharField(max_length=255)),
                ('question_9', models.CharField(max_length=255)),
                ('question_10', models.CharField(max_length=255)),
                ('question_11', models.CharField(max_length=255)),
                ('question_12', models.CharField(max_length=255)),
                ('question_13', models.CharField(max_length=255)),
                ('question_14', models.CharField(max_length=255)),
                ('question_15', models.CharField(max_length=255)),
                ('question_16', models.CharField(max_length=255)),
                ('question_17', models.CharField(max_length=255)),
                ('question_18', models.CharField(max_length=255)),
                ('question_19', models.CharField(max_length=255)),
                ('question_20', models.CharField(max_length=255)),
                ('question_21', models.CharField(max_length=255)),
                ('question_22', models.CharField(max_length=255)),
                ('question_23', models.CharField(max_length=255)),
                ('question_24', models.CharField(max_length=255)),
            ],
        ),
    ]
