# Generated by Django 5.1 on 2024-08-12 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_briefing'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
