# Generated by Django 5.1 on 2024-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_briefing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
