# Generated by Django 5.1 on 2024-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_briefing_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
