# Generated by Django 5.1.1 on 2025-10-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repasse_numero', models.CharField(blank=True, max_length=64)),
                ('terceiro_nome', models.CharField(blank=True, max_length=256)),
                ('competencia', models.CharField(blank=True, max_length=32)),
                ('cnpj', models.CharField(blank=True, max_length=32)),
                ('previsao_pagamento', models.CharField(blank=True, max_length=32)),
                ('profissional_nome', models.CharField(blank=True, max_length=256)),
                ('especialidade', models.CharField(blank=True, max_length=128)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='remittances/')),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.CharField(blank=True, max_length=64)),
                ('conta', models.CharField(blank=True, max_length=64)),
                ('paciente', models.CharField(blank=True, max_length=256)),
                ('convenio', models.CharField(blank=True, max_length=128)),
                ('categoria', models.CharField(blank=True, max_length=64)),
                ('data', models.CharField(blank=True, max_length=32)),
                ('codigo', models.CharField(blank=True, max_length=64)),
                ('procedimento', models.CharField(blank=True, max_length=512)),
                ('funcao', models.CharField(blank=True, max_length=128)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_produzido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.remittanceheader')),
            ],
        ),
    ]
