# Generated by Django 5.1.1 on 2025-10-10 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('competencia', models.CharField(blank=True, max_length=32)),
                ('source_file', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedurePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=32)),
                ('codigo_original', models.CharField(blank=True, max_length=64)),
                ('descricao', models.CharField(blank=True, max_length=512)),
                ('convenio', models.CharField(blank=True, max_length=128)),
                ('categoria', models.CharField(blank=True, max_length=64)),
                ('funcao', models.CharField(blank=True, max_length=128)),
                ('preco_referencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='reconciliation.pricecatalog')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo', 'convenio'], name='reconciliat_codigo_b21950_idx'), models.Index(fields=['catalog', 'codigo', 'convenio'], name='reconciliat_catalog_aaf493_idx')],
                'unique_together': {('catalog', 'codigo', 'convenio', 'vigencia_inicio', 'vigencia_fim')},
            },
        ),
    ]
