# Generated by Django 5.1.1 on 2025-10-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_pricecatalog_procedureprice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='procedureprice',
            name='reconciliat_codigo_b21950_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedureprice',
            name='reconciliat_catalog_aaf493_idx',
        ),
        migrations.AlterUniqueTogether(
            name='procedureprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='procedureprice',
            name='hospital_cnpj',
            field=models.CharField(blank=True, help_text='CNPJ normalizado (somente dígitos)', max_length=32),
        ),
        migrations.AddField(
            model_name='procedureprice',
            name='hospital_nome',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='procedureprice',
            unique_together={('catalog', 'codigo', 'convenio', 'hospital_cnpj', 'categoria', 'vigencia_inicio', 'vigencia_fim')},
        ),
        migrations.AddIndex(
            model_name='procedureprice',
            index=models.Index(fields=['codigo', 'convenio', 'hospital_cnpj', 'categoria'], name='reconciliat_codigo_2bd5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureprice',
            index=models.Index(fields=['catalog', 'codigo', 'convenio', 'hospital_cnpj', 'categoria'], name='reconciliat_catalog_6d4f43_idx'),
        ),
    ]
